### ISSUE TITLE
Installation and configuration

### ISSUE THREAD

**Issue by array81** [berfenger/cam2mqtt#12]
Is possible have information about how install and configure it to works with more that one camera?

I have installed the docker image and create a config.yml file but when I try to run
`docker run -v /home/array81/cam2mqtt:/config acasal/cam2mqtt`

I get error about config file not found but the config.yml is inside /home/array81/cam2mqtt folder

**Comment by berfenger** [comment]
Hi.
To work with more than one camera, just follow the example file where you can see 2 cameras: `reolink_cam_1` and `onvif_cam_1`. You can add as many as you want keeping the same indentation.
```
cameras:
  cam_1:
    host: 192.168.4.1
    ...
  cam_2:
    host: 192.168.4.2
    ...
  cam_3:
    host: 192.168.4.3
    ...
```
To run the docker container on a single command, you need to mount the config file as volume, instead of the directory.
`$ docker run -v "/home/array81/cam2mqtt/config.yml:/config.yml" acasal/cam2mqtt`
You can simplify the command autodetecting the current directory.
`$ docker run -v "${PWD}/config.dev.yml:/config.yml" acasal/cam2mqtt`
Keep in mind that running a container like this will keep the container created once the process is finished. Just add `--rm` to remove the container once the process is finished.
`$ docker run --rm -v "${PWD}/config.dev.yml:/config.yml" acasal/cam2mqtt`

I recommend to use docker-compose because it helps with most of the inconveniencies of running docker containers through command line.

**Comment by array81** [comment]
Hi, thanks for your reply.
I'll use docker compose but before I'd like understand if cofig file is ok so I try to use single command like and I get an error about config file parse. My file is a valid YAML file. This is my config file (I have remove only username and password), I have 3 ONVIF camera:

```
mqtt:
  host: 192.168.188.98
  port: 1883
  username: XXX
  password: XXX
  #base_name: cam2mqtt
  ssl: false
  #required: true # leave it on true (default) to avoid losing messages on startup

cameras:
  cam_motion_taverna:
    host: 192.168.188.52
    username: XXX
    password: XXX
    modules:
      onvif:
        port: 80
        monitor_events: true
        prefer_webhook_subscription: false

  cam_motion_soggiorno:
    host: 192.168.188.54
    username: XXX
    password: XXX
    modules:
      onvif:
        port: 80
        monitor_events: true
        prefer_webhook_subscription: false

  cam_motion_mansarda:
    host: 192.168.188.53
    username: XXX
    password: XXX
    modules:
      onvif:
        port: 80
        monitor_events: true
        prefer_webhook_subscription: false
```
