### ISSUE TITLE
Reolink RLC-810A

### ISSUE THREAD

**Issue by curana** [berfenger/cam2mqtt#17]
Hi,

I set up one RLC-810A and would like to receive not just motion but the AI detection events.

```
cameras:
  reolink_carport:
    host: <ip>
    username: <username>
    password: <password>
    modules:
      onvif:
        port: 8000
        monitor_events: true
        prefer_webhook_subscription: false
      reolink:
        # port: 443 # optional. 443/HTTPS by default
        # username: bob # optional. Alternative username for Reolink API
        # password: bobpass # optional. Alternative password for Reolink API
        # ssl: false # optional. Use ssl/HTTPS
        ai_detection_mode: continous # one of [off, on_motion, continuous]. on_motion requires onvif module to detect motion
        sync_datetime: false
        # audio: false # allow to control audio alarm volume (can't be autodetected)
        # alarm: false # allow to control alarm siren (can't be autodetected)
        # spotlight: false # allow to control spotlight (can't be autodetected)
```

Is this config correct?

In the log it says
```
[INFO ] 2023-01-14 13:04:32,359 akka://cam2mqtt/user/cameraman/cam_reolink_carport/mod_onvif - ONVIF Capabilities for camera reolink_carport:
Events: true
Pull-Point subscription: true
[INFO ] 2023-01-14 13:04:36,196 akka://cam2mqtt/user/cameraman/cam_reolink_carport/mod_reolink - Reolink Capabilities for camera reolink_carport:
```

From the README I am not sure if this configuration is the best for RLC-XXXA cameras. My firmware is v3.1.0.956_22041503, hardware IPC_523128M8MP.

Thanks for some feedback on this.

**Comment by berfenger** [comment]
Hi, the config looks correct, but there seems to be a problem with the Reolink capabilities detection.
Also, there is a typo on your config `continous` should be `continuous`.
```yaml
      onvif:
        port: 8000
        monitor_events: true
        prefer_webhook_subscription: false
      reolink:
        port: 443 # optional. 443/HTTPS by default
        ssl: true # optional. Use ssl/HTTPS
        ai_detection_mode: continuous # one of [off, on_motion, continuous]. on_motion requires onvif module to detect motion
        sync_datetime: false
```

Also, ensure that the camera can be accessed through port 443 (HTTPS) and that the provided user is an admin instead of a simple user. Only admins can change config using the HTTP API.
